### ISSUE TITLE
Getting started instructions needed

### ISSUE THREAD

**Issue by magland** [ahbarnett/mwrapdemo#1]
Here's what I did, as a naive user. (or worse, as someone who thought they knew what they were doing)

I opened MATLAB cd to mwrapdemo, and ran "testall". Of course I got an error, and it also put me in the "c/" directory, I didn't like that.

So I went to the terminal and typed "make". That also gave me an error, and again put me in the "c/" directory. I again did not like that.

So, I thought, maybe it depends on mwrap. > sudo apt-get install mwrap.

That took a while.

Then looking at the c/makefile, I realized I needed to modify it to find the /usr/bin/mwrap. (Shouldn't modify tracked file anyway).

Then I got the same make error, and realized that I probably didn't need mwrap after all (not sure).

Then I read that you can't call "mex" from outside MATLAB console. But you can't issue "make" from inside MATLAB console. So I'm confused.

So I went back into my MATLAB and figured out to do

> > cd c
> > mex gateway.c lib.c
> > test

So, a getting started guide is needed.

**Comment by ahbarnett** [comment]
Hi Jeremy, I'm explaining more about the setup, as you suggest. But I don't understand why typing make from the terminal failed - are you on linux? Did it not find mex? (which can be run in a usual shell). The c/makefile should not have to be modified, since MWRAP points to ../mwrap-0.33.3/mwrap, which is shipped in the repo. More later,  Alex

**Comment by magland** [comment]
You are right. I just didn't have the right path set up in my terminal, so it didn't find mex command. Works now.

**Comment by ahbarnett** [comment]
I will put a user step to test if mex is available first!
Since you don't recommend the user editing tracked files, I will put a top-level include file that the user can adjust their mex and mwrap executable locations.
