### ISSUE TITLE
Getting started problems

### ISSUE THREAD

**Issue by magland** [ahbarnett/mwrapdemo#2]
I realize you direct me to the mwrap docs for compilation problems, but the below is the error I get FYI. Also, I found it easy to "sudo apt-get install mwrap" and then I just change MWRAP=mwrap. You could consider providing these simpler instructions, since it is nice to have mwrap as a global binary. In fact, that is probably better if users will use this for their own projects.

Also I get the following make error:
make[1]: gfortran: Command not found
So that should be listed as a dependency.

Here's the error for making mwrap:
make[1]: flex: Command not found
Makefile:22: recipe for target 'lex.yy.c' failed
But again, I'd recommend telling user to install mwrap globally.

**Comment by ahbarnett** [comment]
Ok, done as suggested. However, your definition of "simpler" is not the same as mine.
For instance, "sudo apt-get install mwrap" fails on my standard ubuntu 12.04 distro.
We have to trust that when eg "flex" isn't found, a user will go and install it.
I made the compilers, and everything else, painfully explicit now.

**Comment by magland** [comment]
Installs beautifully. One typo:
If they exist prematurely --> If they exit prematurely
Also, that note probably not needed -- but I appreciate you bending to my complaints. :)

Nice examples. But to be honest, it is difficult for me to wrap (no pun intended) my head around the makefile logic. I can see what it all does when I focus, but it is difficult to keep track of the source files vs. the generated files. I feel like all the behind-the-scenes stuff should be in a build directory. Not sure if that is possible, but it would clarify some things for me. Also, not sure if the makefile could be simplified at all. The mex_id_ was confusing and I wasn't sure about "gateway", it seems it is a special mwrap word. Seems like a learning curve. At this point, I would choose to go with traditional raw mex, unless I can be convinced to dive in and get past the initial learning phase.

**Comment by ahbarnett** [comment]
Yes it does add one level of abstraction, but you will find it _much_ quicker than writing/debugging (yuk) your own mex interface. If there is a way to package stuff away better, I'd love to know. mex_id_ is just some mathworks thing. The name "gateway" is arbitrary; I chose it since it serves as a gateway to the library. The idea is using this repo as a template gets you going. See you tomorrow! Alex

**Comment by magland** [comment]
Okay. At some point I'll try to put something together that makes the
procedure more seamless.
J
